### ISSUE TITLE
Can you have a look at a new CSV parser benchmark?

### ISSUE THREAD

**Issue by josdejong** [LeanyLabs/csv-parsers-benchmarks#1]
Hi @Andriy-LL, thanks for writing this [article benchmarking JavaScript CSV parsers](https://leanylabs.com/blog/js-csv-parsers-benchmarks/) two years ago and sharing the tests here on Github.

I was recently searching for a good CSV parser for a web application of mine, but ended up writing new CSV parser named [`csv42`](https://github.com/josdejong/csv42/). It looks like this parser is very fast, faster than the popular libraries in most circumstances, and often with a big margin. I'm quite surprised about that, and a bit in doubt if I'm not overlooking something. Since the CSV standard is so old and there are so many CSV parsers out there, I had expected that the popular libraries would have optimized performance and would be impossible to beat. 

With your past experience comparing CSV parsers, would you be willing to have a look at the benchmark I created to see if I'm not missing something obvious and make sure I'm not comparing apples to oranges?

https://github.com/josdejong/csv42/tree/main/benchmark

Feel free to say no, it's just an open question 😄

**Comment by Andriy-LL** [comment]
Hi @josdejong,

That's a nice little parser you wrote. It seems faster than others, and the code is concise and straightforward. It resembles the code we use in production but with support for nesting and a bit more callbacks.

I think these little parsers are so fast because they do much less validation when parsing. For example, if one row had fewer fields than there should be, most parsers would at least call some error callback. csv42, on the other hand, tries to parse what it can without providing any way of knowing that the input CSV is malformed. Another reason is that some of them are way overengineered, probably to the point that JIT cannot inline most of the calls, producing efficient machine code. Optimization is not a top priority for many of them; they focus on ease of use and stability.

P. S. I've had to add "\n" versions to the quoted expected values in validation tests for benchmarks to run on Linux.

**Comment by josdejong** [comment]
Thanks for the feedback Andriy, and taking the time to run the benchmarks yourself!

Good point about a possible difference in the amount of validation and strictness. I'll think that through. And yeah, some libraries are designed with a totally different goal, like a streaming API with a minimal memory footprint.

I fixed the `\n` issues, thanks for pointing that out.
